import styles from "../styles/Home.module.scss";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to DEX of{" "}
          <a
            href="https://ton.org"
            rel="noopener noreferrer"
            target="_blank"
            title="The Open Network"
          >
            TON
          </a>
        </h1>

        <p className={styles.description}>Placeholder for Home description.</p>

        <div>
          <Link href="/create-pool">
            <span className={styles.card}>Create Pool</span>
          </Link>
          <Link href="/exchange-token">
            <span className={styles.card}>Exchange Token</span>
          </Link>
          <Link href="/liquidity-from-pool">
            <span className={styles.card}>Liquidity from Pool</span>
          </Link>
          <Link href="/pool-statistics">
            <span className={styles.card}>Pool Statistics</span>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
